### ISSUE TITLE
How's the judging coming along?

### ISSUE THREAD

**Issue by ZippoLag** [github/game-off-2013#31]
Hi, first of all, I'm really sorry for asking and I want to say that I'm in no way "demanding judging to be sped up" or anything along those lines.

I've just been looking at the tweets related to the #ggo13 and noticed how people are getting impatient, some even thinking that "it's now ok to keep pushing updates to their projects since the contest is over" or something like that.

I'm well aware of the amount of games submitted and the limited amount of times the judges have between their jobs and the holyday season, but I think a small tweet from @github saying something similar to "Happy Holydays! Our judges are still working on #ggo13 so thanks for standing by for the results" would greatly improve the mood at twitterland.

That's all I came to say, sorry for going all the way and -literally- "making an issue out of this".

Have a happy new year and may the winners be able to rejoice soon!

**Comment by lshulyay** [comment]
Nobody on that has tag has claimed that it was ok to keep pushing updates as far as I can see (a couple of us did discuss making updates, but specified not going live with/pushing anything, maybe that's what you mean?) Also, I think @leereilly commented a few days ago on Twitter that that winners will be announced "real soon", so the small tweet you're talking about has been made (just without the hashtag, which would've been nice to include so that everyone following it would see)

**Comment by ZippoLag** [comment]
I see, perhaps I did misunderstood the tweets coming and going..
Either way, it'd be nice to have an announcement with the hashtag, so I just went ahead and repeated leereilly's tweet with the hashtag added, for now.

**Comment by leereilly** [comment]
Hi @ZippoLag - thanks for raising the issue (and thanks for the retweet to clarify things). I'll definitely take this onboard and make sure things are clearer for `#ggo14`.

We just announced the winners over on the [GitHub Blog](https://github.com/blog/1731-github-game-off-ii-winners):

![](http://i.imgur.com/ZMjXESw.gif)

Enjoy and Happy New Year :tada:

Cheers,
  Lee :beers:
